unbind r
bind r source-file ~/.tmux.conf
bind 4 select-window -t :=4
bind g split-window -h \; split-window -v \; select-pane -L \; split-window -v \; select-layout tiled

set -g prefix C-s

set -g mouse on

set-option -sg escape-time 10

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'

# Minimal tmux status config
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g @minimal-tmux-show-expanded-icon-for-all-tabs true
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""
set -g status-right-length 20
set -g status-left-length 20
set -g @minimal-tmux-use-arrow false
set -g extended-keys on
set -g extended-keys-format csi-u
# Toggle status bar with prefix+b
bind-key b set-option status

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
